### PR TITLE
resolves #11 - Nock testing added for existing API fns

### LINKED ISSUE #11: Improve testing to cover api fn calls
In order to resolve some open issues with confidence in not breaking the library, we need to instrument the api call parts of the library with tests.

See issues: https://github.com/fti-technology/node-skytap/issues/9, https://github.com/fti-technology/node-skytap/issues/5, https://github.com/fti-technology/node-skytap/issues/12

I suggest we use [nock](https://github.com/pgte/nock), as we can test our api calls without modifying library code by hooking into node's http lib directly.

See a sample change here: https://github.com/ftikbogle/node-skytap/blob/MockTests/test/skytap.js

### LINKED ISSUE #14: `environments.all` doesn't work with promises (only callback api)
This is to track this bug. Will be fixed in upcoming testing improvements branch: https://github.com/fti-technology/node-skytap/issues/11

### LINKED ISSUE #15: In some cases, `arghelper.convertReqParams` will add a lone '?' to the end of a request.
If an empty object is passed as params instead of a falsey value this happens.

Added testing and fix in testing improvements branch. Track in issue: https://github.com/fti-technology/node-skytap/issues/11

### LINKED ISSUE #17: Projects `list` adds trailing slash to uri
ex: https://cloud.skytap.com/projects/ instead of https://cloud.skytap.com/projects

Should be latter, to be consistent with the rest of the api calls.

Will fix in #11

### LINKED ISSUE #18: `Skytap.vms.del` does calls PUT and not DELETE
This is being fixed when #11 is merged

### PR DESCRIPTION
**Pull request by ftikbogle**
resolves #14 - `Environments.all` not working with promises
resolves #15 - `arghelper.convertReqParams` may add a ? to the end of a request
resolves #17 - `Projects.list` adds trailing slash to uri
resolves #18 - `Vms.del` calls PUT not DELETE

### CODE REVIEW

File: test/networks.js [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+    it('requests a list of networks associated with an environment', function () {
+      return nockspect(function (nock) {
+        nock.get('/configurations/1/networks').reply(200);
+        return _.bind(skytap.networks.list, skytap.networks, {
+          configuration_id: 1
+        });
+      });
+    });
+
+    // it('requires an environment or template id', function () {
```
Comment (ftikbogle) [inline test/networks.js]: I left this test commented out. We should probably think of enforcing specific arguments instead of shooting off an incomplete uri to skytap.

Comment (ftikbogle) [inline test/networks.js]: Keeping this commented out. We should probably check requires args before sending an incomplete uri off to skytap...

Comment (bmancini55) [inline test/networks.js]: Yeah I'm of two minds on that.  We currently don't do required arg checking and could  add it as an enhancement.  

But... I'm not entirely sure it's worth it though as long as we're properly handling API failure responses.

**Comment by bmancini55** [comment]
Looks great. I'll merge first thing tomorrow and bump the version number.

File: test/environments.js [hunk 2]
```diff
@@ -0,0 +1,183 @@
...
+
+    it('checks an environments runstate', function () {
+      return nockspect(function (nock) {
+        nock.get(testUri).reply(200, { runstate: 'running' });
+        return testFn;
+      });
+    });
+
+    it('polls for environment to start', function () {
+      // Note: `waitForState` is currently hardcoded to wait 5s before trying again
```
Comment (ftikbogle) [inline test/environments.js]: This is another problem with the tests. With no way to configure the timeout, this test takes 10 seconds *at least*, which really slows down running validate. We may want to file an issue to improve this in the future.
